package schema_output;
import schemas.*;

/**
 * The control variable summary generated by the forward model.
 * @author Prateek Tandon
 *
 */
public class ControlVariableSummary {
	
	/**
	 * The forward model that sent the summary.
	 */
	private ForwardModel sender;
	
	/**
	 * The hand's distance from the center of the hammer.
	 */
	private double distanceFromCenter;

	/**
	 * The orientation difference between the knuckle  vector
	 * and the hammer handle vector.
	 */
	private double orientationDifference;

	/**
	 * The current time step
	 */
	private int timeStep;
	
	/**
	 * Constructor
	 * @param sender
	 * @param distanceFromCenter
	 * @param orientationDifference
	 * @param timeStep
	 */
	public ControlVariableSummary(ForwardModel sender, double distanceFromCenter, double orientationDifference, int timeStep) {
		this.sender = sender;
		this.distanceFromCenter = distanceFromCenter;
		this.orientationDifference = orientationDifference;
		this.timeStep = timeStep;
	}
	
	/**
	 * @return the sender
	 */
	public ForwardModel getSender() {
		return sender;
	}
	/**
	 * @param sender the sender to set
	 */
	public void setSender(ForwardModel sender) {
		this.sender = sender;
	}
	/**
	 * @return the distanceFromCenter
	 */
	public double getDistanceFromCenter() {
		return distanceFromCenter;
	}
	/**
	 * @param distanceFromCenter the distanceFromCenter to set
	 */
	public void setDistanceFromCenter(double distanceFromCenter) {
		this.distanceFromCenter = distanceFromCenter;
	}
	/**
	 * @return the orientationDifference
	 */
	public double getOrientationDifference() {
		return orientationDifference;
	}
	/**
	 * @param orientationDifference the orientationDifference to set
	 */
	public void setOrientationDifference(double orientationDifference) {
		this.orientationDifference = orientationDifference;
	}

	/**
	 * @return the timeStep
	 */
	public int getTimeStep() {
		return timeStep;
	}

	/**
	 * @param timeStep the timeStep to set
	 */
	public void setTimeStep(int timeStep) {
		this.timeStep = timeStep;
	}
}
